const fs = require('fs');
const path = require('path');

const locales = ['en', 'id', 'de', 'fr', 'it', 'es', 'pt', 'ko', 'hi', 'ja'];

const newTranslations = {
  backToDashboard: { en: '← Back to Dashboard', id: '← Kembali ke Dashboard', de: '← Zurück zum Dashboard', fr: '← Retour au tableau de bord', it: '← Torna alla Dashboard', es: '← Volver al Panel', pt: '← Voltar ao Painel', ko: '← 대시보드로 돌아가기', hi: '← डैशबोर्ड पर वापस जाएं', ja: '← ダッシュボードに戻る' },
  settingsTitle: { en: 'Settings', id: 'Pengaturan', de: 'Einstellungen', fr: 'Paramètres', it: 'Impostazioni', es: 'Configuración', pt: 'Configurações', ko: '설정', hi: 'सेटिंग्स', ja: '設定' },
  profileAkun: { en: 'Account Profile', id: 'Profil Akun', de: 'Kontoprofil', fr: 'Profil du compte', it: 'Profilo Account', es: 'Perfil de Cuenta', pt: 'Perfil de Conta', ko: '계정 프로필', hi: 'खाता प्रोफ़ाइल', ja: 'アカウントプロファイル' },
  keamanan: { en: 'Security', id: 'Keamanan', de: 'Sicherheit', fr: 'Sécurité', it: 'Sicurezza', es: 'Seguridad', pt: 'Segurança', ko: '보안', hi: 'सुरक्षा', ja: 'セキュリティ' },
  tampilan: { en: 'Appearance', id: 'Tampilan', de: 'Aussehen', fr: 'Apparence', it: 'Aspetto', es: 'Apariencia', pt: 'Aparência', ko: '디자인', hi: 'प्रकटन', ja: '外観' },
  notifikasi: { en: 'Notifications', id: 'Notifikasi', de: 'Benachrichtigungen', fr: 'Notifications', it: 'Notifiche', es: 'Notificaciones', pt: 'Notificações', ko: '알림', hi: 'सूचनाएं', ja: '通知' },
  fullNameLabel: { en: 'Full Name', id: 'Nama Lengkap', de: 'Vollständiger Name', fr: 'Nom complet', it: 'Nome Completo', es: 'Nombre Completo', pt: 'Nome Completo', ko: '이름', hi: 'पूरा नाम', ja: 'フルネーム' },
  emailLabel: { en: 'Email Address', id: 'Alamat Email', de: 'E-Mail-Adresse', fr: 'Adresse e-mail', it: 'Indirizzo Email', es: 'Correo Electrónico', pt: 'Endereço de E-mail', ko: '이메일 주소', hi: 'ईमेल पता', ja: 'メールアドレス' },
  emailChangeNotice: { en: 'Contact support to change your email address.', id: 'Hubungi dukungan pelanggan untuk mengubah alamat email Anda.', de: 'Wenden Sie sich an den Support, um Ihre E-Mail-Adresse zu ändern.', fr: 'Contactez le support untuk modifier votre adresse e-mail.', it: 'Contatta il supporto per modificare il tuo indirizzo email.', es: 'Póngase en contacto con el soporte para cambiar su correo.', pt: 'Entre em contato com o suporte para alterar seu e-mail.', ko: '이메일 주소를 변경하려면 고객 지원팀에 문의하세요.', hi: 'अपना ईमेल पता बदलने के लिए सहायता टीम से संपर्क करें।', ja: 'メールアドレスを変更するには、サポートにお問い合わせください。' },
  profilePhotoLabel: { en: 'Profile Photo', id: 'Foto Profil', de: 'Profilbild', fr: 'Photo de profil', it: 'Foto Profilo', es: 'Foto de Perfil', pt: 'Foto de Perfil', ko: '프로필 사진', hi: 'प्रोफ़ाइल फ़ोटो', ja: 'プロフィール写真' },
  changePhotoBtn: { en: 'Change Photo', id: 'Ubah Foto', de: 'Bild ändern', fr: 'Modifier la photo', it: 'Cambia Foto', es: 'Cambiar Foto', pt: 'Alterar Foto', ko: '사진 변경', hi: 'फोटो बदलें', ja: '写真を変更' },
  saveChangesBtn: { en: 'Save Changes', id: 'Simpan Perubahan', de: 'Änderungen speichern', fr: 'Sauvegarder les modifications', it: 'Salva Modifiche', es: 'Guardar Cambios', pt: 'Salvar Alterações', ko: '변경 사항 저장', hi: 'बदलाव सहेजें', ja: '変更を保存' },
  helpCenterTitle: { en: 'Help Center', id: 'Pusat Bantuan', de: 'Hilfe-Center', fr: 'Centre d\'aide', it: 'Centro Assistenza', es: 'Centro de Ayuda', pt: 'Central de Ajuda', ko: '고객 센터', hi: 'सहायता केंद्र', ja: 'ヘルプセンター' },
  searchPlaceholder: { en: 'Search guides or ask anything...', id: 'Cari panduan atau tanya sesuatu...', de: 'Anleitungen suchen oder Fragen stellen...', fr: 'Rechercher des guides ou poser des questions...', it: 'Cerca guide o chiedi qualcosa...', es: 'Buscar guías o preguntar algo...', pt: 'Pesquisar guias ou perguntar algo...', ko: '가이드 검색 또는 질문하기...', hi: 'गाइड खोजें या कुछ भी पूछें...', ja: 'ガイドを検索するか、質問してください...' },
  popularTopicsTitle: { en: 'Popular Topics', id: 'Topik Populer', de: 'Beliebte Themen', fr: 'Sujets populaires', it: 'Argomenti Popolari', es: 'Temas Populares', pt: 'Tópicos Populares', ko: '인기 주제', hi: 'लोकप्रिय विषय', ja: 'よくある質問' },
  topic1Text: { en: 'How to connect WhatsApp Business API', id: 'Cara menghubungkan nomor WhatsApp', de: 'So verbinden Sie die WhatsApp Business API', fr: 'Comment connecter l\'API WhatsApp Business', it: 'Come collegare le API di WhatsApp Business', es: 'Cómo conectar la API de WhatsApp Business', pt: 'Como conectar a API do WhatsApp Business', ko: 'WhatsApp 비즈니스 API 연결 방법', hi: 'व्हाट्सएप बिजनेस एपीआई को कैसे कनेक्ट करें', ja: 'WhatsApp Business APIの接続方法' },
  topic2Text: { en: 'Configuring and Optimizing Knowledge Base', id: 'Mengatur Knowledge Base', de: 'Konfigurieren und Optimieren der Wissensdatenbank', fr: 'Configuration et optimisation de la base de connaissances', it: 'Configurazione e ottimizzazione della Knowledge Base', es: 'Configuración y optimización de la Base de Conocimiento', pt: 'Configurando e otimizando a Base de Conhecimento', ko: '지식 기반 구성 및 최적화', hi: 'ज्ञान आधार को कॉन्फ़िगर और अनुकूलित करना', ja: 'ナレッジベースの設定と最適化' },
  topic3Text: { en: 'Billing cycles, invoices & plans', id: 'Masalah penagihan & faktur', de: 'Abrechnungszyklen, Rechnungen & Pläne', fr: 'Cycles de facturation, factures et forfaits', it: 'Cicli di fatturazione, fatture e piani', es: 'Ciclos de facturación, facturas y planes', pt: 'Ciclos de faturamento, faturas e planos', ko: '결제 주기, 인보이스 및 요금제', hi: 'बिलिंग चक्र, चालान और योजनाएं', ja: '請求サイクル、請求書、およびプラン' },
  topic4Text: { en: 'Understanding Webhook Data Formats', id: 'Format Data Webhook', de: 'Webhook-Datenformate verstehen', fr: 'Comprendre les formats de données Webhook', it: 'Informazioni sui formati dei dati Webhook', es: 'Comprender los formatos de datos de Webhook', pt: 'Compreendendo os formatos de dados do Webhook', ko: '웹훅 데이터 형식 이해', hi: 'वेबहुक डेटा प्रारूपों को समझना', ja: 'Webhookデータ形式の理解' },
  moreHelpTitle: { en: 'Need more help?', id: 'Butuh bantuan lebih lanjut?', de: 'Benötigen Sie weitere Hilfe?', fr: 'Besoin d\'aide supplémentaire ?', it: 'Serve ulteriore aiuto?', es: '¿Necesita más ayuda?', pt: 'Precisa de mais ajuda?', ko: '추가 도움이 필요하십니까?', hi: 'और सहायता चाहिये?', ja: 'さらにヘルプが必要ですか？' },
  moreHelpDesc: { en: 'Our support team is here to help 24/7. Create a support ticket and we will respond via email.', id: 'Tim dukungan kami siap membantu Anda 24/7. Buat tiket dukungan dan kami akan merespons melalui email.', de: 'Unser Support-Team ist rund um die Uhr für Sie da. Erstellen Sie ein Ticket, und wir antworten per E-Mail.', fr: 'Notre équipe d\'assistance est là 24h/24, 7j/7. Créez un ticket et nous vous répondrons par e-mail.', it: 'Il nostro team di supporto è disponibile 24/7. Apri un ticket e risponderemo via email.', es: 'Nuestro equipo de soporte está aquí 24/7. Cree un ticket de soporte y responderemos por correo.', pt: 'Nossa equipe de suporte está aqui 24/7. Crie um ticket e responderemos por e-mail.', ko: '지원 팀은 연중무휴로 대기하고 있습니다. 지원 티켓을 생성하시면 이메일로 응답해 드립니다.', hi: 'हमारी सहायता टीम 24/7 यहाँ है। एक सहायता टिकट बनाएं और हम ईमेल के माध्यम से जवाब देंगे।', ja: 'サポートチームは24時間年中無休で対応しています。サポートチケットを作成していただければ、メールで返信いたします。' },
  submitTicketBtn: { en: 'Submit Support Ticket', id: 'Kirim Tiket Bantuan', de: 'Support-Ticket senden', fr: 'Soumettre un ticket d\'assistance', it: 'Invia Ticket di Supporto', es: 'Enviar Ticket de Soporte', pt: 'Enviar Ticket de Suporte', ko: '지원 티켓 제출', hi: 'सहायता टिकट भेजें', ja: 'サポートチケットを送信' },
  upgradePlanTitle: { en: 'Upgrade your plan', id: 'Tingkatkan paket Anda', de: 'Upgrade Ihres Tarifs', fr: 'Améliorez votre forfait', it: 'Migliora il tuo piano', es: 'Actualice su plan', pt: 'Atualize seu plano', ko: '요금제 업그레이드', hi: 'अपनी योजना अपग्रेड करें', ja: 'プランのアップグレード' },
  upgradePlanSub: { en: 'Choose the plan that fits your business scale.', id: 'Pilih paket yang sesuai dengan kebutuhan skala bisnis Anda.', de: 'Wählen Sie den Tarif, der zu Ihrer Unternehmensgröße passt.', fr: 'Choisissez le forfait qui convient à la taille de votre entreprise.', it: 'Scegli il piano più adatto alla scala del tuo business.', es: 'Elija el plan que se adapte a la escala de su negocio.', pt: 'Escolha o plano que se adapta à escala do seu negócio.', ko: '비즈니스 규모에 맞는 요금제를 선택하세요.', hi: 'वह योजना चुनें जो आपके व्यवसाय के पैमाने के अनुकूल हो।', ja: 'ビジネスの規模に合ったプランを選択してください。' },
  freePlan: { en: 'Free', id: 'Free', de: 'Kostenlos', fr: 'Gratuit', it: 'Gratuito', es: 'Gratis', pt: 'Gratuito', ko: '무료', hi: 'नि: शुल्क', ja: '無料' },
  proPlan: { en: 'Pro', id: 'Pro', de: 'Pro', fr: 'Pro', it: 'Pro', es: 'Pro', pt: 'Pro', ko: '프로', hi: 'प्रो', ja: 'プロ' },
  enterprisePlan: { en: 'Enterprise', id: 'Enterprise', de: 'Enterprise', fr: 'Entreprise', it: 'Enterprise', es: 'Enterprise', pt: 'Enterprise', ko: '엔터프라이즈', hi: 'एंटरप्राइज', ja: 'エンタープライズ' },
  currentPlanBtn: { en: 'Current Plan', id: 'Paket Anda Saat Ini', de: 'Aktueller Tarif', fr: 'Forfait actuel', it: 'Piano Attuale', es: 'Plan Actual', pt: 'Plano Atual', ko: '현재 요금제', hi: 'वर्तमान योजना', ja: '現在のプラン' },
  upgradeToProBtn: { en: 'Upgrade to Pro', id: 'Tingkatkan ke Pro', de: 'Auf Pro upgraden', fr: 'Passer à Pro', it: 'Migliora a Pro', es: 'Actualizar a Pro', pt: 'Atualizar para Pro', ko: 'Pro로 업그레이드', hi: 'प्रो में अपग्रेड करें', ja: 'Proにアップグレード' },
  contactUsBtn: { en: 'Contact Us', id: 'Hubungi Kami', de: 'Kontaktieren Sie uns', fr: 'Nous contacter', it: 'Contattaci', es: 'Contáctenos', pt: 'Contate-nos', ko: '문의하기', hi: 'संपर्क करें', ja: 'お問い合わせ' },
  learnMoreTitle: { en: 'Learn More', id: 'Pelajari lebih lanjut', de: 'Mehr erfahren', fr: 'En savoir plus', it: 'Scopri di più', es: 'Saber más', pt: 'Saiba Mais', ko: '더 알아보기', hi: 'अधिक जानें', ja: '詳細情報' },
  learnMoreDesc: { en: 'Regalia AI is an enterprise-grade autonomous customer service platform. We help automate customer interactions on WhatsApp Business using the latest generative AI models.', id: 'Regalia AI adalah platform layanan pelanggan otonom tingkat enterprise. Kami membantu mengotomatisasi interaksi pelanggan di WhatsApp Business dengan menggunakan model AI generatif terkini.', de: 'Regalia AI ist eine autonome Kundenservice-Plattform für Unternehmen. Wir helfen dabei, Kundeninteraktionen auf WhatsApp Business mithilfe neuester generativer KI-Modelle zu automatisieren.', fr: 'Regalia AI est une plateforme de service client autonome de qualité entreprise. Nous aidons à automatiser les interactions avec les clients sur WhatsApp Business en utilisant les derniers modèles d\'IA générative.', it: 'Regalia AI è una piattaforma di assistenza clienti autonoma di livello enterprise. Aiutiamo ad automatizzare le interazioni con i clienti su WhatsApp Business utilizzando i più recenti modelli di IA generativa.', es: 'Regalia AI es una plataforma de servicio al cliente autónoma de nivel empresarial. Ayudamos a automatizar las interacciones con los clientes en WhatsApp Business utilizando los últimos modelos de IA generativa.', pt: 'Regalia AI é uma plataforma de atendimento ao cliente autônoma de nível empresarial. Ajudamos a automatizar as interações com os clientes no WhatsApp Business usando os modelos de IA generativos mais recentes.', ko: 'Regalia AI는 엔터프라이즈급 자율 고객 서비스 플랫폼입니다. 최신 생성형 AI 모델을 사용하여 WhatsApp Business에서 고객 상호 작용을 자동화할 수 있도록 지원합니다.', hi: 'Regalia AI एक एंटरप्राइज-ग्रेड स्वायत्त ग्राहक सेवा मंच है। हम नवीनतम जनरेटिव एआई मॉडल का उपयोग करके व्हाट्सएप बिजनेस पर ग्राहक इंटरैक्शन को स्वचालित करने में मदद करते हैं।', ja: 'Regalia AIは、エンター프ライズグレードの自律型カスタマーサービスプラットフォームです。最新の生成AIモデルを使用して、WhatsApp Businessでの顧客との対話を自動化します。' },
  gettingStartedGuide: { en: 'Getting Started Guide', id: 'Panduan Memulai', de: 'Leitfaden für den Einstieg', fr: 'Guide de démarrage', it: 'Guida Introduttiva', es: 'Guía de Inicio', pt: 'Guia de Introdução', ko: '시작 가이드', hi: 'शुरुआती गाइड', ja: 'スタートガイド' },
  gettingStartedDesc: { en: 'Learn how to connect WhatsApp API and configure system prompts/knowledge base for your agent.', id: 'Pelajari cara menyambungkan WhatsApp API dan mengatur pengetahuan dasar (Knowledge Base) untuk agen Anda.', de: 'Erfahren Sie, wie Sie die WhatsApp-API verbinden und System-Prompts/Wissensdatenbanken für Ihren Agenten konfigurieren.', fr: 'Découvrez comment connecter l\'API WhatsApp et configurer les prompts système/la base de connaissances de votre agent.', it: 'Scopri come collegare le API di WhatsApp e configurare i prompt di sistema/knowledge base per il tuo agente.', es: 'Aprenda a conectar la API de WhatsApp y a configurar las instrucciones del sistema/base de conocimiento para su agente.', pt: 'Saiba como conectar a API do WhatsApp e configurar prompts do sistema/base de conhecimento para o seu agente.', ko: 'WhatsApp API를 연결하고 에이전트의 시스템 프롬프트/지식 기반을 구성하는 방법을 알아보세요.', hi: 'व्हाट्सएप एपीआई को कनेक्ट करना और अपने एजेंट के लिए सिस्टम प्रॉम्प्ट/ज्ञान संदर्भ कॉन्फ़िगर करना सीखें।', ja: 'WhatsApp APIを接続し、エージェントのシステムプロンプト/ナレッジベースを設定する方法を学びます。' },
  apiDocumentation: { en: 'API Documentation', id: 'Dokumentasi API', de: 'API-Dokumentation', fr: 'Documentation de l\'API', it: 'Documentazione API', es: 'Documentación de la API', pt: 'Documentação da API', ko: 'API 문서', hi: 'एपीआई दस्तावेज़', ja: 'APIドキュメント' },
  apiDocDesc: { en: 'Integrate Regalia with your CRM or internal systems using webhooks and REST API.', id: 'Integrasikan Regalia dengan CRM atau sistem internal Anda menggunakan webhook dan REST API.', de: 'Integrieren Sie Regalia mithilfe von Webhooks und der REST-API in Ihr CRM- oder internes System.', fr: 'Intégrez Regalia à votre CRM ou à vos systèmes internes à l\'aide de webhooks et de l\'API REST.', it: 'Integra Regalia con il tuo CRM o sistemi interni utilizzando webhook e REST API.', es: 'Integre Regalia con su CRM o sistemas internos utilizando webhooks y la API REST.', pt: 'Integre o Regalia com seu CRM ou sistemas internos usando webhooks e API REST.', ko: '웹훅 및 REST API를 사용하여 Regalia를 CRM 또는 내부 시스템과 통합하십시오.', hi: 'वेबहुक और REST API का उपयोग करके Regalia को अपने CRM या आंतरिक प्रणालियों के साथ एकीकृत करें।', ja: 'WebhookとREST APIを使用して、Regaliaをご使用のCRMまたは社内システムと統合します。' }
};

locales.forEach(lang => {
  const file = path.join(__dirname, `src/locales/${lang}.json`);
  let data = {};
  if(fs.existsSync(file)) {
    data = JSON.parse(fs.readFileSync(file, 'utf8'));
  }
  for (const key in newTranslations) {
    data[key] = newTranslations[key][lang] || newTranslations[key]['en'];
  }
  fs.writeFileSync(file, JSON.stringify(data, null, 2));
});
console.log('Updated separate pages locales!');
