import os
import sys
import unittest
import asyncio
import re

# Ensure standard output uses UTF-8 to avoid encoding issues with emojis on Windows
if sys.platform.startswith('win'):
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

# Add the current directory to sys.path so we can import internal modules
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

import agent
from database import get_any_first_client

class TestAgentIntegration(unittest.TestCase):
    def setUp(self):
        # Save original references
        self.original_generate_content = agent.client.models.generate_content
        self.original_cek_ongkir = agent.cek_ongkir
        self.original_buat_tiket_komplain = agent.buat_tiket_komplain
        
        # Spy lists to track function invocations
        self.cek_ongkir_calls = []
        self.buat_tiket_calls = []
        
        # Wrap/spy on cek_ongkir
        def spy_cek_ongkir(destination):
            self.cek_ongkir_calls.append(destination)
            return self.original_cek_ongkir(destination)
        agent.cek_ongkir = spy_cek_ongkir
        
        # Wrap/spy on buat_tiket_komplain
        def spy_buat_tiket(resi_number):
            self.buat_tiket_calls.append(resi_number)
            return self.original_buat_tiket_komplain(resi_number)
        agent.buat_tiket_komplain = spy_buat_tiket

        # Define a mock response object
        class MockResponse:
            def __init__(self, text):
                self.text = text
                
        # Mock implementation of generate_content
        def mock_generate_content(model, contents, config=None):
            user_msg = contents[-1].parts[0].text
            system_instruction = config.system_instruction if config else ""
            
            # Case 1: Skincare Product Consultation
            if "jerawat batu" in user_msg or "minyakan" in user_msg:
                # We recommend "Acne Clear Serum"
                text_reply = (
                    "Halo Kak! Buat kulit yang gampang minyakan dan jerawat batu karena haid, "
                    "kami sangat menyarankan Acne Clear Serum (salicylic acid 2% + niacinamide) seharga Rp 89.000. "
                    "Ini ampuh banget buat kempesin jerawat tapi ga bikin kulit kering. Ada yang mau ditanya lagi kak?"
                )
                return MockResponse(text_reply)
                
            # Case 2: Shipping check (COD) in Javanese dialect
            elif "cibadak" in user_msg.lower() or "ongkir" in user_msg.lower() or "piye" in user_msg.lower():
                # Trigger the cek_ongkir function
                shipping_info = agent.cek_ongkir("Cibadak, Sukabumi")
                text_reply = (
                    f"Matur nuwun sampun narosaken, Kak. Nggih, saged COD dhateng kecamatan Cibadak, Sukabumi. "
                    f"{shipping_info} Wonten ingkang saget dipunbantu malih?"
                )
                return MockResponse(text_reply)
                
            # Case 3: Delivery Complaint
            elif "nyangkut" in user_msg or "nyampe-nyampe" in user_msg or "gimana sih" in user_msg:
                # Extract the voucher code generated by agent.py from the system instructions
                voucher_match = re.search(r"REG[A-Z0-9]{5}", system_instruction)
                voucher_code = voucher_match.group(0) if voucher_match else "REGDUMMY"
                
                # Trigger buat_tiket_komplain with a dummy or extracted resi number
                ticket_info = agent.buat_tiket_komplain("JP123456789")
                text_reply = (
                    f"Aduh, mohon maaf sekali ya kak atas kendalanya. Pesenan kakak yang nyangkut di gudang sortir "
                    f"akan segera kami proses. {ticket_info} Sebagai bentuk penyesalan, "
                    f"ini ada voucher khusus buat kakak: {voucher_code} yang bisa dipakai buat potongan harga berikutnya. "
                    f"Semoga berkenan ya kak!"
                )
                return MockResponse(text_reply)
                
            return MockResponse("Halo kak, ada yang bisa kami bantu?")
            
        agent.client.models.generate_content = mock_generate_content
        
        # Retrieve client data from database
        self.client_data = get_any_first_client()
        assert self.client_data is not None, "Client data must exist in database. Ensure init_db is run."

    def tearDown(self):
        # Restore original functions
        agent.client.models.generate_content = self.original_generate_content
        agent.cek_ongkir = self.original_cek_ongkir
        agent.buat_tiket_komplain = self.original_buat_tiket_komplain

    def test_case_1_product_consultation_slang(self):
        print("\n=== Running Case 1: Product Consultation with Slang ===")
        user_msg = "Kak, muka aku gampang minyakan terus skrg lg banyak jerawat batu gr2 mau haid. Pake paketan yg mana ya yg cpt kempesin jerawat tp ga bikin kering?"
        
        # Call the agent logic
        response = asyncio.run(agent.get_ai_response(self.client_data, "user_phone_1", user_msg))
        
        print(f"User: {user_msg}")
        print(f"Agent: {response}")
        
        # Verification: Assert the agent recommends the right product from the database
        self.assertIn("Acne Clear Serum", response, "Should recommend Acne Clear Serum")

    def test_case_2_shipping_check_javanese(self):
        print("\n=== Running Case 2: Shipping Check (COD) in Javanese Dialect ===")
        user_msg = "Kak ini bisa COD ke kecamatan Cibadak, Sukabumi ga? Trus ongkirnya piye?"
        
        # Call the agent logic
        response = asyncio.run(agent.get_ai_response(self.client_data, "user_phone_2", user_msg))
        
        print(f"User: {user_msg}")
        print(f"Agent: {response}")
        
        # Verification: Assert 'cek_ongkir' function is triggered
        self.assertEqual(len(self.cek_ongkir_calls), 1, "cek_ongkir function should be called exactly once")
        self.assertIn("Cibadak", self.cek_ongkir_calls[0])
        
        # Verification: Assert it returns shipping info (Rp 12.000 for Cibadak/Sukabumi)
        self.assertIn("12.000", response, "Should return shipping info containing Rp 12.000")

    def test_case_3_delivery_complaint_anger(self):
        print("\n=== Running Case 3: Delivery Complaint (Negative Sentiment) ===")
        user_msg = "Mbak gimana sih, pesenan saya udah 4 hari ga nyampe-nyampe, pas dicek resinya nyangkut di gudang sortir! Nyesel belanja di sini!"
        
        # Verification: Assert that anger/negative sentiment is detected
        self.assertTrue(agent.detect_anger(user_msg), "Anger sentiment should be detected")
        
        # Call the agent logic
        response = asyncio.run(agent.get_ai_response(self.client_data, "user_phone_3", user_msg))
        
        print(f"User: {user_msg}")
        print(f"Agent: {response}")
        
        # Verification: Assert 'buat_tiket_komplain' is triggered
        self.assertEqual(len(self.buat_tiket_calls), 1, "buat_tiket_komplain should be called exactly once")
        
        # Verification: Assert that a voucher code starting with 'REG' is offered in the response
        voucher_match = re.search(r"REG[A-Z0-9]{5}", response)
        self.assertIsNotNone(voucher_match, "Should offer a voucher code starting with 'REG'")
        print(f"Voucher code offered: {voucher_match.group(0)}")

if __name__ == "__main__":
    unittest.main()
