// termsTranslations.js — Full multilingual dictionary for Terms of Service (10 languages)

export const termsContent = {
  en: {
    title: 'Customer Terms of Service',
    effective: 'Effective 16 July 2026 · Regalia AI WhatsApp Agent SaaS Platform',
    previousVersion: 'Previous Version',
    intro: 'These Customer Terms of Service ("Terms") govern your access to and commercial use of the Regalia AI autonomous WhatsApp customer service platform accessing the application programming interfaces, user interfaces, and routing algorithms. By registering or connecting your WhatsApp Business Phone Number ID, you agree to be bound by these Terms.',
    sections: [
      {
        heading: '1. Platform Scope & AI Autonomous Processing',
        p: 'Regalia AI provides a software-as-a-service (SaaS) solution designed to automate customer service inquiries on WhatsApp using large language models. Once activated, our backend automatically ingests webhook payloads from Meta and generates contextual replies based on your configured knowledge base and dialect rules.'
      },
      {
        heading: '2. Meta WhatsApp Business API Compliance & Anti-Spam Obligations',
        p: 'You explicitly warrant and agree that your utilization of the Regalia SaaS platform shall strictly adhere to the Meta WhatsApp Business Terms of Service and Meta Anti-Spam Guidelines:',
        list: [
          'You shall not use Regalia AI to transmit unsolicited bulk broadcasts, unauthorized promotional blasts, or fraudulent communications.',
          'You must obtain verifiable opt-in consent from end-customers prior to initiating outbound automated WhatsApp conversations.',
          'You remain solely liable for any account restrictions, quality rating drops, or bans imposed by Meta as a consequence of improper message volume or policy non-compliance.'
        ]
      },
      {
        heading: '3. Ownership of Inputs, Knowledge Base & AI Outputs',
        p: 'As between you and Regalia AI, you retain all right, title, and intellectual property interest in and to your business credentials (, ), custom knowledge base documents, and customer prompt inputs ("Customer Inputs"). You likewise own all automated response content generated by our AI agent on your behalf ("AI Outputs"). We claim no proprietary ownership over your custom product pricing, FAQs, or customer communication history.'
      },
      {
        heading: '4. Human-in-the-Loop Supervisory Responsibility',
        p: 'While Regalia AI models are rigorously engineered to provide accurate, helpful, and polite support, artificial intelligence systems may occasionally encounter edge cases or hallucinations. You acknowledge that:',
        list: [
          'You are responsible for monitoring real-time WebSocket dashboard alerts such as system alerts or fallback triggers.',
          'You agree to utilize the human takeover mechanism when an issue exceeds AI confidence thresholds.',
          'Regalia AI shall not be held liable for commercial losses resulting from unverified automated statements regarding pricing, stock levels, or delivery promises.'
        ]
      },
      {
        heading: '5. Service Level Agreement (SLA) & Availability',
        p: 'We endeavor to maintain 99.9% availability for our FastAPI webhook processing server and real-time dashboard connection. However, platform performance is contingent upon the continuous availability of third-party infrastructure, including Meta\'s WhatsApp Graph API endpoints and Google DeepMind\'s Gemini cloud inference servers. Temporary disruptions caused by third-party upstream providers do not constitute a breach of these Terms.'
      },
      {
        heading: '6. Limitation of Liability & Indemnification',
        p: 'To the maximum extent permitted by applicable law, neither Regalia AI nor its affiliates shall be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business goodwill arising from your use of the autonomous WhatsApp agent. You agree to defend, indemnify, and hold harmless Regalia AI against any third-party claims or regulatory fines originating from your violation of Meta WhatsApp Business policies or applicable privacy statutes.'
      },
      {
        heading: '7. Governing Law & Contact',
        p: 'These Terms of Service are governed by applicable commercial laws without regard to conflict of law principles. For administrative inquiries, enterprise SLA customization, or legal notices, please contact our counsel at legal@regalia.ai.'
      }
    ]
  },
  id: {
    title: 'Syarat dan Ketentuan Layanan',
    effective: 'Berlaku sejak 16 Juli 2026 · Platform SaaS Agen WhatsApp Regalia AI',
    previousVersion: 'Versi Sebelumnya',
    intro: 'Syarat dan Ketentuan Layanan Pelanggan ("Ketentuan") ini mengatur akses serta penggunaan komersial Anda atas platform layanan pelanggan WhatsApp otonom Regalia AI yang mencakup antarmuka pemrograman aplikasi, antarmuka pengguna, dan algoritma perutean. Dengan mendaftar atau menghubungkan ID Nomor Telepon WhatsApp Business Anda, Anda setuju untuk terikat oleh Ketentuan ini.',
    sections: [
      {
        heading: '1. Ruang Lingkup Platform & Pemrosesan Otonom AI',
        p: 'Regalia AI menyediakan solusi software-as-a-service (SaaS) yang dirancang untuk mengotomatiskan layanan pelanggan di WhatsApp menggunakan model bahasa besar. Setelah diaktifkan, sistem backend kami secara otomatis menerima payload webhook dari Meta dan menghasilkan balasan kontekstual berdasarkan basis pengetahuan serta aturan gaya bahasa yang Anda konfigurasi (`toggle_slang`, `toggle_java`, `toggle_ongkir`, `toggle_anger`, dan `toggle_fallback`).'
      },
      {
        heading: '2. Kepatuhan Meta WhatsApp Business API & Kewajiban Anti-Spam',
        p: 'Anda secara tegas menjamin dan setuju bahwa penggunaan Anda atas platform SaaS Regalia harus sepenuhnya mematuhi Ketentuan Layanan Meta WhatsApp Business dan Pedoman Anti-Spam Meta:',
        list: [
          'Anda dilarang menggunakan Regalia AI untuk mengirimkan siaran massal (broadcast) yang tidak diminta, promosi tanpa izin, atau pesan yang bersifat menipu/penipuan.',
          'Anda wajib memperoleh persetujuan (opt-in consent) yang dapat diverifikasi dari pelanggan akhir sebelum memulai percakapan WhatsApp otomatis.',
          'Anda bertanggung jawab penuh atas segala pembatasan akun, penurunan peringkat kualitas (quality rating), atau pemblokiran yang dijatuhkan oleh Meta akibat volume pesan yang tidak wajar atau pelanggaran kebijakan.'
        ]
      },
      {
        heading: '3. Kepemilikan Input, Basis Pengetahuan & Output AI',
        p: 'Antara Anda dan Regalia AI, Anda memegang seluruh hak, kepemilikan, dan kekayaan intelektual atas kredensial bisnis Anda (, ), dokumen basis pengetahuan khusus, serta prompt pelanggan ("Input Pelanggan"). Anda juga memiliki seluruh konten respons otomatis yang dihasilkan oleh agen AI kami atas nama bisnis Anda ("Output AI"). Kami tidak mengklaim kepemilikan apa pun atas harga produk, FAQ, atau riwayat komunikasi pelanggan Anda.'
      },
      {
        heading: '4. Tanggung Jawab Pengawasan Human-in-the-Loop',
        p: 'Meskipun model Regalia AI telah dirancang dengan cermat untuk memberikan balasan yang akurat, membantu, dan sopan, sistem kecerdasan buatan sesekali dapat menghadapi kasus tepi (edge cases) atau halusinasi. Anda mengakui bahwa:',
        list: [
          'Anda bertanggung jawab untuk memantau peringatan dasbor WebSocket secara real-time seperti peringatan sistem atau kegagalan penanganan.',
          'Anda setuju untuk memanfaatkan mekanisme pengambilalihan manusia (Human Takeover) ketika suatu masalah melampaui ambang keyakinan AI.',
          'Regalia AI tidak bertanggung jawab atas kerugian komersial yang timbul dari balasan otomatis yang belum diverifikasi mengenai harga, ketersediaan stok, atau janji pengiriman.'
        ]
      },
      {
        heading: '5. Perjanjian Tingkat Layanan (SLA) & Ketersediaan',
        p: 'Kami berupaya mempertahankan ketersediaan 99.9% untuk server pemrosesan webhook FastAPI dan koneksi dasbor real-time. Namun, kinerja platform bergantung pada ketersediaan berkelanjutan infrastruktur pihak ketiga, termasuk endpoint Meta WhatsApp Graph API dan server inferensi cloud Google DeepMind Gemini. Gangguan sementara yang disebabkan oleh penyedia infrastruktur hulu pihak ketiga tidak merupakan pelanggaran atas Ketentuan ini.'
      },
      {
        heading: '6. Batasan Tanggung Jawab & Ganti Rugi',
        p: 'Sejauh diizinkan oleh hukum yang berlaku, Regalia AI maupun afiliasinya tidak bertanggung jawab atas kerugian tidak langsung, insidental, khusus, atau punitif, termasuk hilangnya keuntungan, data, atau reputasi bisnis yang timbul dari penggunaan Anda atas agen WhatsApp otonom. Anda setuju untuk membela dan membebaskan Regalia AI dari klaim pihak ketiga atau denda regulasi yang berasal dari pelanggaran Anda terhadap kebijakan Meta WhatsApp Business atau undang-undang privasi yang berlaku.'
      },
      {
        heading: '7. Hukum yang Berlaku & Kontak',
        p: 'Syarat dan Ketentuan Layanan ini diatur oleh hukum komersial yang berlaku. Untuk pertanyaan administratif, kustomisasi SLA enterprise, atau pemberitahuan hukum, silakan hubungi penasihat hukum kami di legal@regalia.ai.'
      }
    ]
  },
  de: {
    title: 'Allgemeine Geschäftsbedingungen für Kunden',
    effective: 'Gültig ab 16. Juli 2026 · Regalia AI WhatsApp-Agenten-SaaS-Plattform',
    previousVersion: 'Vorherige Version',
    intro: 'Diese Allgemeinen Geschäftsbedingungen für Kunden („Bedingungen“) regeln Ihren Zugang zu und die kommerzielle Nutzung der autonomen WhatsApp-Kundendienstplattform Regalia AI einschließlich Anwendungsprogrammierschnittstellen, Benutzeroberflächen und Routing-Algorithmen. Durch die Registrierung oder Verknüpfung Ihrer WhatsApp Business-Telefonnummer-ID erklären Sie sich mit diesen Bedingungen einverstanden.',
    sections: [
      {
        heading: '1. Plattformumfang & autonome KI-Verarbeitung',
        p: 'Regalia AI bietet eine Software-as-a-Service (SaaS)-Lösung an, die zur Automatisierung von Kundendienstanfragen auf WhatsApp unter Verwendung großer Sprachmodelle entwickelt wurde. Nach der Aktivierung verarbeitet unser Backend automatisch Webhook-Nutzlasten von Meta und generiert kontextuelle Antworten basierend auf Ihrer konfigurierten Wissensdatenbank und Dialektregeln.'
      },
      {
        heading: '2. Einhaltung der Meta WhatsApp Business API & Anti-Spam-Pflichten',
        p: 'Sie versichern ausdrücklich und stimmen zu, dass Ihre Nutzung der Regalia SaaS-Plattform streng den Nutzungsbedingungen von Meta WhatsApp Business und den Anti-Spam-Richtlinien von Meta entspricht:',
        list: [
          'Sie dürfen Regalia AI nicht zum Versenden unerwünschter Massennachrichten, unautorisierter Werbesendungen oder betrügerischer Mitteilungen verwenden.',
          'Sie müssen eine nachweisbare Opt-in-Zustimmung von Endkunden einholen, bevor Sie ausgehende automatisierte WhatsApp-Gespräche initiieren.',
          'Sie haften allein für alle Kontoeinschränkungen, Qualitätsbewertungsrückgänge oder Sperren, die von Meta aufgrund unangemessenen Nachrichtenvolumens oder Richtlinienverstößen verhängt werden.'
        ]
      },
      {
        heading: '3. Eigentum an Eingaben, Wissensdatenbank & KI-Ausgaben',
        p: 'Im Verhältnis zwischen Ihnen und Regalia AI behalten Sie alle Rechte, Eigentumstitel und geistigen Eigentumsrechte an Ihren Geschäftskredentialen (, ), benutzerdefinierten Wissensdatenbankdokumenten und Kunden-Prompt-Eingaben („Kundeneingaben“). Ebenso besitzen Sie alle automatisierten Antwortinhalte, die von unserem KI-Agenten in Ihrem Namen generiert werden („KI-Ausgaben“). Wir erheben keinen Eigentumsanspruch auf Ihre benutzerdefinierten Produktpreise, FAQs oder die Kommunikationshistorie mit Kunden.'
      },
      {
        heading: '4. Human-in-the-Loop Aufsichtsverantwortung',
        p: 'Obwohl die KI-Modelle von Regalia AI sorgfältig entwickelt wurden, um präzise, hilfreiche und höfliche Unterstützung zu bieten, können Systeme der künstlichen Intelligenz gelegentlich auf Grenzfälle oder Halluzinationen stoßen. Sie erkennen an, dass:',
        list: [
          'Sie für die Überwachung der Echtzeit-WebSocket-Dashboard-Warnungen wie Systemwarnungen oder Fallback-Auslöser verantwortlich sind.',
          'Sie zustimmen, den menschlichen Übernahmememechanismus (Human Takeover) zu nutzen, wenn ein Problem die Schwellenwerte für KI-Zuversicht überschreitet.',
          'Regalia AI nicht für kommerzielle Verluste haftbar gemacht werden kann, die resultierend aus ungeprüften automatisierten Aussagen bezüglich Preisen, Lagerbeständen oder Lieferzusagen entstehen.'
        ]
      },
      {
        heading: '5. Service Level Agreement (SLA) & Verfügbarkeit',
        p: 'We bestreben uns, eine Verfügbarkeit von 99.9% für unseren FastAPI-Webhook-Verarbeitungsserver und die Echtzeit-Dashboard-Verbindung aufrechtzuerhalten. Die Leistung der Plattform hängt jedoch von der kontinuierlichen Verfügbarkeit der Infrastruktur Dritter ab, einschließlich der WhatsApp Graph API-Endpunkte von Meta und der Gemini-Cloud-Interferenzserver von Google DeepMind. Vorübergehende Unterbrechungen durch vorgelagerte Drittanbieter stellen keinen Verstoß gegen diese Bedingungen dar.'
      },
      {
        heading: '6. Haftungsbeschränkung & Schadloshaltung',
        p: 'Soweit nach geltendem Recht zulässig, haften weder Regalia AI noch seine verbundenen Unternehmen für indirekte, zufällige, besondere, Folgeschäden oder Strafschadenersatz, einschließlich Verlust von Gewinnen, Daten oder Firmenwert, die aus Ihrer Nutzung des autonomen WhatsApp-Agenten entstehen. Sie erklären sich damit einverstanden, Regalia AI gegenüber allen Ansprüchen Dritter oder behördlichen Geldstrafen zu verteidigen und schadlos zu halten, die aus Ihrem Verstoß gegen Meta WhatsApp Business-Richtlinien oder geltende Datenschutzgesetze resultieren.'
      },
      {
        heading: '7. Geltendes Recht & Kontakt',
        p: 'Diese Allgemeinen Geschäftsbedingungen unterliegen dem geltenden Handelsrecht unter Ausschluss der Kollisionsnormen. Für administrative Anfragen, Enterprise-SLA-Anpassungen oder rechtliche Mitteilungen wenden Sie sich bitte an unsere Rechtsabteilung unter legal@regalia.ai.'
      }
    ]
  },
  fr: {
    title: 'Conditions Générales d\'Utilisation',
    effective: 'En vigueur le 16 juillet 2026 · Plateforme SaaS d\'agent WhatsApp Regalia AI',
    previousVersion: 'Version précédente',
    intro: 'Les présentes Conditions générales d\'utilisation client (« Conditions ») régissent votre accès et votre utilisation commerciale de la plateforme de service client autonome WhatsApp Regalia AI (points de terminaison `port 8000`, interface du tableau de bord et routage de l\'agent IA Gemini). En vous inscrivant ou en connectant votre identifiant de numéro de téléphone WhatsApp Business, vous acceptez d\'être lié par les présentes Conditions.',
    sections: [
      {
        heading: '1. Portée de la plateforme et traitement autonome de l\'IA',
        p: 'Regalia AI fournit une solution logicielle en tant que service (SaaS) conçue pour automatiser les demandes de service client sur WhatsApp à l\'aide de grands modèles de langage. Une fois activé, notre système back-end ingère automatiquement les charges utiles webhook de Meta et génère des réponses contextuelles basées sur votre base de connaissances configurée et vos règles de dialecte.'
      },
      {
        heading: '2. Conformité à l\'API Meta WhatsApp Business et obligations anti-spam',
        p: 'Vous garantissez explicitement et acceptez que votre utilisation de la plateforme SaaS Regalia respecte strictement les Conditions d\'utilisation de Meta WhatsApp Business et les Directives anti-spam de Meta :',
        list: [
          'Vous ne devez pas utiliser Regalia AI pour transmettre des diffusions en masse non sollicitées, des campagnes promotionnelles non autorisées ou des communications frauduleuses.',
          'Vous devez obtenir un consentement préalable et vérifiable (opt-in) des clients finaux avant d\'initier des conversations WhatsApp automatisées sortantes.',
          'Vous demeurez seul responsable de toute restriction de compte, baisse de note de qualité ou suspension imposée par Meta en conséquence d\'un volume de messages inapproprié ou du non-respect des politiques.'
        ]
      },
      {
        heading: '3. Propriété des entrées, de la base de connaissances et des sorties IA',
        p: 'Entre vous et Regalia AI, vous conservez tous les droits, titres et intérêts de propriété intellectuelle sur vos identifiants professionnels (, ), vos documents de base de connaissances personnalisés et les invites clients (« Entrées client »). De même, vous possédez tout le contenu des réponses automatisées généré par notre agent IA en votre nom (« Sorties IA »). Nous ne revendiquons aucune propriété sur la tarification de vos produits, vos FAQ ou l\'historique de communication de vos clients.'
      },
      {
        heading: '4. Responsabilité de supervision Human-in-the-Loop',
        p: 'Bien que les modèles de Regalia AI soient rigoureusement conçus pour fournir un support précis, utile et poli, les systèmes d\'intelligence artificielle peuvent parfois rencontrer des cas limites ou des hallucinations. Vous reconnaissez que :',
        list: [
          'Vous êtes responsable de la surveillance en temps réel des alertes du tableau de bord WebSocket tels que les alertes système ou les déclencheurs de secours.',
          'Vous acceptez d\'utiliser le mécanisme de prise en main humaine (Human Takeover) lorsqu\'un problème dépasse les seuils de confiance de l\'IA.',
          'Regalia AI ne saurait être tenue responsable des pertes commerciales résultant de déclarations automatisées non vérifiées concernant les prix, les niveaux de stock ou les promesses de livraison.'
        ]
      },
      {
        heading: '5. Accord de niveau de service (SLA) et disponibilité',
        p: 'Nous nous efforçons de maintenir une disponibilité de 99.9% pour notre serveur de traitement webhook FastAPI et la connexion au tableau de bord en temps réel. Cependant, les performances de la plateforme dépendent de la disponibilité continue de l\'infrastructure tierce, notamment les points de terminaison de l\'API Meta WhatsApp Graph et les serveurs d\'inférence cloud Gemini de Google DeepMind. Les interruptions temporaires causées par les fournisseurs tiers en amont ne constituent pas une violation de ces Conditions.'
      },
      {
        heading: '6. Limitation de responsabilité et indemnisation',
        p: 'Dans toute la mesure permise par la loi applicable, ni Regalia AI ni ses affiliés ne pourront être tenus responsables des dommages indirects, accessoires, spéciaux, consécutifs ou punitifs, y compris la perte de bénéfices, de données ou de clientèle découlant de votre utilisation de l\'agent WhatsApp autonome. Vous acceptez de défendre, d\'indemniser et de dégager de toute responsabilité Regalia AI contre toute réclamation de tiers ou amende réglementaire provenant de votre violation des politiques de Meta WhatsApp Business ou des lois sur la protection des données applicables.'
      },
      {
        heading: '7. Droit applicable et contact',
        p: 'Les présentes Conditions générales d\'utilisation sont régies par les lois commerciales applicables sans égard aux principes de conflit de lois. Pour toute question administrative, personnalisation de SLA d\'entreprise ou notification juridique, veuillez contacter notre conseiller juridique à legal@regalia.ai.'
      }
    ]
  },
  it: {
    title: 'Termini e Condizioni del Servizio',
    effective: 'In vigore dal 16 luglio 2026 · Piattaforma SaaS per Agenti WhatsApp Regalia AI',
    previousVersion: 'Versione precedente',
    intro: 'I presenti Termini e Condizioni del Servizio ("Termini") disciplinano l\'accesso e l\'utilizzo commerciale della piattaforma di assistenza clienti autonoma WhatsApp Regalia AI (endpoint `port 8000`, interfaccia dashboard e instradamento dell\'agente IA Gemini). Registrandosi o collegando il proprio ID numero di telefono WhatsApp Business, l\'utente accetta di essere vincolato ai presenti Termini.',
    sections: [
      {
        heading: '1. Ambito della Piattaforma e Elaborazione Autonoma IA',
        p: 'Regalia AI fornisce una soluzione software-as-a-service (SaaS) progettata per automatizzare le richieste di assistenza clienti su WhatsApp utilizzando grandi modelli di linguaggio. Una volta attivato, il nostro backend acquisisce automaticamente i payload webhook da Meta e genera risposte contestuali basate sulla base di conoscenza configurata e sulle regole di dialetto.'
      },
      {
        heading: '2. Conformità all\'API Meta WhatsApp Business e Obblighi Anti-Spam',
        p: 'L\'utente garantisce esplicitamente e accetta che l\'utilizzo della piattaforma SaaS Regalia debba aderire rigorosamente ai Termini di servizio di Meta WhatsApp Business e alle Linee guida Anti-Spam di Meta:',
        list: [
          'L\'utente non deve utilizzare Regalia AI per trasmettere trasmissioni di massa non richieste, promozioni non autorizzate o comunicazioni fraudolente.',
          'L\'utente deve ottenere un consenso opt-in verificabile dai clienti finali prima di avviare conversazioni WhatsApp automatizzate in uscita.',
          'L\'utente rimane l\'unico responsabile per eventuali restrizioni dell\'account, cali della valutazione di qualità o blocchi imposti da Meta a conseguenza di un volume di messaggi improprio o del mancato rispetto delle normative.'
        ]
      },
      {
        heading: '3. Proprietà degli Input, della Base di Conoscenza e degli Output IA',
        p: 'Tra l\'utente e Regalia AI, l\'utente mantiene ogni diritto, titolo e interesse di proprietà intellettuale sulle proprie credenziali aziendali (, ), sui documenti della base di conoscenza personalizzata e sugli input dei clienti ("Input Cliente"). Allo stesso modo, l\'utente possiede tutti i contenuti di risposta automatizzata generati dal nostro agente IA per suo conto ("Output IA"). Non rivendichiamo alcuna proprietà sui prezzi dei prodotti, sulle FAQ o sulla cronologia delle comunicazioni dei clienti.'
      },
      {
        heading: '4. Responsabilità di Supervisione Human-in-the-Loop',
        p: 'Sebbene i modelli di Regalia AI siano rigorosamente progettati per fornire supporto accurato, utile ed educato, i sistemi di intelligenza artificiale possono talvolta riscontrare casi limite o allucinazioni. L\'utente riconosce che:',
        list: [
          'L\'utente è responsabile del monitoraggio degli avvisi della dashboard WebSocket in tempo reale come avvisi di sistema o trigger di emergenza.',
          'L\'utente accetta di utilizzare il meccanismo di subentro umano (Human Takeover) quando un problema supera le soglie di sicurezza dell\'IA.',
          'Regalia AI non sarà ritenuta responsabile per perdite commerciali derivanti da dichiarazioni automatizzate non verificate relative a prezzi, livelli di inventario o promesse di consegna.'
        ]
      },
      {
        heading: '5. Accordo sul Livello di Servizio (SLA) e Disponibilità',
        p: 'Ci adoperiamo per mantenere una disponibilità del 99.9% per il nostro server di elaborazione webhook FastAPI e la connessione alla dashboard in tempo reale. Tuttavia, le prestazioni della piattaforma dipendono dalla disponibilità continua dell\'infrastruttura di terze parti, inclusi gli endpoint dell\'API Meta WhatsApp Graph e i server di inferenza cloud Gemini di Google DeepMind. Le interruzioni temporanee causate da fornitori di infrastrutture terzi non costituiscono una violazione dei presenti Termini.'
      },
      {
        heading: '6. Limitazione di Responsabilità e Indennizzo',
        p: 'Nella misura massima consentita dalla legge applicabile, né Regalia AI né i suoi affiliati saranno responsabili per danni indiretti, incidentali, speciali, consequenziali o punitivi, inclusa la perdita di profitti, dati o avviamento aziendale derivanti dall\'uso dell\'agente WhatsApp autonomo. L\'utente accetta di difendere, indennizzare e tenere indenne Regalia AI da qualsiasi rivendicazione di terzi o sanzione normativa derivante dalla violazione delle politiche di Meta WhatsApp Business o delle leggi sulla protezione dei dati applicabili.'
      },
      {
        heading: '7. Legge Applicabile e Contatti',
        p: 'I presenti Termini e Condizioni del Servizio sono regolati dalle leggi commerciali applicabili senza riguardo ai principi di conflitto di leggi. Per richieste amministrative, personalizzazione SLA aziendali o note legali, contattare il nostro ufficio legale all\'indirizzo legal@regalia.ai.'
      }
    ]
  },
  es: {
    title: 'Términos de Servicio para Clientes',
    effective: 'Vigente desde el 16 de julio de 2026 · Plataforma SaaS de Agente de WhatsApp Regalia AI',
    previousVersion: 'Versión anterior',
    intro: 'Estos Términos de Servicio para Clientes ("Términos") regulan su acceso y uso comercial de la plataforma de atención al cliente autónoma por WhatsApp de Regalia AI que incluye interfaces de programación de aplicaciones, interfaces de usuario y algoritmos de enrutamiento. Al registrarse o conectar su ID de número de teléfono de WhatsApp Business, acepta quedar vinculado por estos Términos.',
    sections: [
      {
        heading: '1. Alcance de la Plataforma y Procesamiento Autónomo de IA',
        p: 'Regalia AI proporciona una solución de software como servicio (SaaS) diseñada para automatizar las consultas de atención al cliente en WhatsApp utilizando grandes modelos de lenguaje. Una vez activado, nuestro backend recibe automáticamente las cargas útiles de webhooks de Meta y genera respuestas contextuales en función de su base de conocimientos configurada y reglas de dialecto.'
      },
      {
        heading: '2. Cumplimiento de la API de Meta WhatsApp Business y Obligaciones Anti-Spam',
        p: 'Usted garantiza explícitamente y acepta que su uso de la plataforma SaaS de Regalia cumplirá estrictamente con los Términos de Servicio de Meta WhatsApp Business y las Directrices Anti-Spam de Meta:',
        list: [
          'No debe utilizar Regalia AI para transmitir envíos masivos no solicitados, promociones no autorizadas o comunicaciones fraudulentas.',
          'Debe obtener un consentimiento de suscripción verificable (opt-in) de los clientes finales antes de iniciar conversaciones automatizadas salientes por WhatsApp.',
          'Usted sigue siendo el único responsable de cualquier restricción de cuenta, caída en la calificación de calidad o suspensión impuesta por Meta como consecuencia de un volumen de mensajes inadecuado o del incumplimiento de las políticas.'
        ]
      },
      {
        heading: '3. Propiedad de las Entradas, Base de Conocimientos y Salidas de la IA',
        p: 'Entre usted y Regalia AI, usted conserva todo el derecho, título e interés de propiedad intelectual de sus credenciales comerciales (, ), documentos de base de conocimientos personalizados y las solicitudes de los clientes ("Entradas del Cliente"). Asimismo, es propietario de todo el contenido de respuesta automatizada generado por nuestro agente de IA en su nombre ("Salidas de IA"). No reclamamos ninguna propiedad sobre sus precios, preguntas frecuentes o historial de comunicaciones con clientes.'
      },
      {
        heading: '4. Responsabilidad de Supervisión Human-in-the-Loop',
        p: 'Si bien los modelos de Regalia AI están rigurosamente diseñados para brindar un soporte preciso, útil y amable, los sistemas de inteligencia artificial pueden encontrar ocasionalmente casos límite o alucinaciones. Usted reconoce que:',
        list: [
          'Es responsable de monitorear las alertas en tiempo real en el panel de control de WebSocket como alertas de sistema o disparadores de respaldo.',
          'Acepta utilizar el mecanismo de intervención humana (Human Takeover) cuando un problema supere los umbrales de confianza de la IA.',
          'Regalia AI no será responsable de pérdidas comerciales resultantes de declaraciones automatizadas no verificadas sobre precios, niveles de inventario o promesas de entrega.'
        ]
      },
      {
        heading: '5. Acuerdo de Nivel de Servicio (SLA) y Disponibilidad',
        p: 'Nos esforzamos por mantener una disponibilidad del 99.9% en nuestro servidor de procesamiento de webhooks de FastAPI y en la conexión en tiempo real del panel. Sin embargo, el rendimiento de la plataforma depende de la disponibilidad continua de infraestructura de terceros, incluidos los puntos de conexión de la API Graph de Meta y los servidores de inferencia en la nube Gemini de Google DeepMind. Las interrupciones temporales causadas por proveedores de infraestructura no constituyen un incumplimiento de estos Términos.'
      },
      {
        heading: '6. Limitación de Responsabilidad e Indemnización',
        p: 'En la máxima medida permitida por la ley aplicable, ni Regalia AI ni sus afiliados serán responsables por daños indirectos, incidentales, especiales, consecuentes o punitivos, incluida la pérdida de ganancias, datos o fondo de comercio resultantes del uso del agente de WhatsApp autónomo. Acepta defender, indemnizar y eximir de responsabilidad a Regalia AI de reclamos de terceros o multas regulatorias derivadas del incumplimiento de las políticas de Meta WhatsApp Business o las leyes de privacidad aplicables.'
      },
      {
        heading: '7. Ley Aplicable y Contacto',
        p: 'Estos Términos de Servicio para Clientes se rigen por las leyes comerciales aplicables sin tener en cuenta los principios de conflicto de leyes. Para consultas administrativas, personalización de SLA empresarial o avisos legales, comuníquese con nuestro departamento legal en legal@regalia.ai.'
      }
    ]
  },
  pt: {
    title: 'Termos de Serviço para Clientes',
    effective: 'Em vigor a partir de 16 de julho de 2026 · Plataforma SaaS de Agente WhatsApp Regalia AI',
    previousVersion: 'Versão anterior',
    intro: 'Estes Termos de Serviço para Clientes ("Termos") regem seu acesso e uso comercial da plataforma de atendimento ao cliente autônoma no WhatsApp Regalia AI que inclui interfaces de programação de aplicativos, interfaces de usuário e algoritmos de roteamento. Ao registrar ou conectar sua ID de número de telefone do WhatsApp Business, você concorda em se vincular a estes Termos.',
    sections: [
      {
        heading: '1. Escopo da Plataforma e Processamento Autônomo por IA',
        p: 'A Regalia AI fornece uma solução de software como serviço (SaaS) projetada para automatizar solicitações de atendimento ao cliente no WhatsApp usando grandes modelos de linguagem. Uma vez ativado, nosso backend processa automaticamente os payloads de webhook da Meta e gera respostas contextuais com base na sua base de conhecimento configurada e nas regras de dialeto.'
      },
      {
        heading: '2. Conformidade com a API Meta WhatsApp Business e Obrigações Anti-Spam',
        p: 'Você garante explicitamente e concorda que a utilização da plataforma SaaS Regalia deve aderir estritamente aos Termos de Serviço do Meta WhatsApp Business e às Diretrizes Anti-Spam da Meta:',
        list: [
          'Você não deve usar a Regalia AI para transmitir disparos em massa não solicitados, promoções não autorizadas ou comunicações fraudulentas.',
          'Você deve obter consentimento de aceitação (opt-in) verificável dos clientes finais antes de iniciar conversas automatizadas ativas pelo WhatsApp.',
          'Você permanece o único responsável por quaisquer restrições de conta, quedas de classificação de qualidade ou bloqueios impostos pela Meta como consequência de volume impróprio de mensagens ou violação das políticas.'
        ]
      },
      {
        heading: '3. Propriedade das Entradas, Base de Conhecimento e Saídas da IA',
        p: 'Entre você e a Regalia AI, você retém todo o direito, título e interesse de propriedade intelectual em suas credenciais corporativas (, ), documentos personalizados da base de conhecimento e entradas dos clientes ("Entradas do Cliente"). Da mesma forma, você possui todo o conteúdo de resposta automatizada gerado pelo nosso agente de IA em seu nome ("Saídas da IA"). Não reivindicamos nenhuma propriedade sobre seus preços, perguntas frequentes ou histórico de comunicação dos clientes.'
      },
      {
        heading: '4. Responsabilidade de Supervisão Human-in-the-Loop',
        p: 'Embora os modelos da Regalia AI sejam rigorosamente projetados para fornecer suporte preciso, útil e educado, os sistemas de inteligência artificial podem ocasionalmente encontrar casos limítrofes ou alucinações. Você reconhece que:',
        list: [
          'Você é responsável por monitorar alertas em tempo real no painel WebSocket como alertas de sistema ou gatilhos de contingência.',
          'Você concorda em utilizar o mecanismo de intervenção humana (Human Takeover) quando um problema exceder os limites de confiança da IA.',
          'A Regalia AI não será responsabilizada por perdas comerciais resultantes de declarações automatizadas não verificadas relativas a preços, níveis de estoque ou promessas de entrega.'
        ]
      },
      {
        heading: '5. Acordo de Nível de Serviço (SLA) e Disponibilidade',
        p: 'Buscamos manter 99.9% de disponibilidade em nosso servidor de processamento de webhook FastAPI e na conexão em tempo real do painel. No entanto, o desempenho da plataforma depende da disponibilidade contínua de infraestrutura de terceiros, incluindo os endpoints da API Meta WhatsApp Graph e os servidores de inferência em nuvem Gemini do Google DeepMind. Interrupções temporárias causadas por fornecedores upstream não constituem violação destes Termos.'
      },
      {
        heading: '6. Limitação de Responsabilidade e Indenização',
        p: 'Até o limite máximo permitido pela lei aplicável, nem a Regalia AI nem suas afiliadas serão responsáveis por danos indiretos, incidentais, especiais, consequenciais ou punitivos, incluindo perda de lucros, dados ou fundo de comércio resultantes do seu uso do agente WhatsApp autônomo. Você concorda em defender, indenizar e isentar a Regalia AI de quaisquer reclamações de terceiros ou multas regulatórias originadas pela sua violação das políticas do Meta WhatsApp Business ou das leis de privacidade aplicáveis.'
      },
      {
        heading: '7. Lei Aplicável e Contato',
        p: 'Estes Termos de Serviço para Clientes são regidos pelas leis comerciais aplicáveis, sem consideração a conflitos de leis. Para consultas administrativas, personalização de SLA corporativo ou avisos legais, entre em contato com nosso setor jurídico em legal@regalia.ai.'
      }
    ]
  },
  ko: {
    title: '고객 서비스 약관',
    effective: '시행일: 2026년 7월 16일 · Regalia AI WhatsApp 에이전트 SaaS 플랫폼',
    previousVersion: '이전 버전',
    intro: '본 고객 서비스 약관("약관")은 Regalia AI 자율 WhatsApp 고객 서비스 플랫폼응용 프로그램 프로그래밍 인터페이스, 사용자 인터페이스 및 라우팅 알고리즘을 포함하여에 대한 귀하의 접근 및 상업적 사용을 규정합니다. 귀하가 WhatsApp Business 전화번호 ID를 등록하거나 연결함으로써 본 약관의 구속을 받는 데 동의합니다.',
    sections: [
      {
        heading: '1. 플랫폼 범위 및 AI 자율 처리',
        p: 'Regalia AI는 대형 언어 모델을 사용하여 WhatsApp 상의 고객 서비스 문의를 자동화하도록 설계된 서비스형 소프트웨어(SaaS) 솔루션을 제공합니다. 활성화되면 당사 백엔드는 Meta의 웹훅 페이로드를 자동으로 수신하고 설정된 지식 기반 및 사투리 규칙에 기반한 문맥적 답변을 생성합니다.'
      },
      {
        heading: '2. Meta WhatsApp Business API 준수 및 스팸 방지 의무',
        p: '귀하는 Regalia SaaS 플랫폼 사용 시 Meta WhatsApp Business 서비스 약관 및 Meta 스팸 방지 가이드라인을 엄격히 준수할 것을 명시적으로 보증하고 동의합니다:',
        list: [
          '귀하는 요청되지 않은 대량 브로드캐스트, 무단 프로모션 메시지 또는 사기성 통신을 전송하기 위해 Regalia AI를 사용해서는 안 됩니다.',
          '귀하는 발신 자동 WhatsApp 대화를 시작하기 전에 최종 고객으로부터 사전 동의(옵트인)를 확실히 받아야 합니다.',
          '귀하는 부적절한 메시지 양이나 정책 위반의 결과로 Meta가 부과하는 모든 계정 제한, 품질 등급 하락 또는 차단에 대해 단독으로 책임집니다.'
        ]
      },
      {
        heading: '3. 입력, 지식 기반 및 AI 출력의 소유권',
        p: '귀하와 Regalia AI 사이에서 귀하는 비즈니스 자격 증명(, ), 맞춤형 지식 기반 문서 및 고객 프롬프트 입력("고객 입력")에 대한 모든 권리, 소유권 및 지적 재산권을 유지합니다. 마찬가지로 귀하는 당사 AI 에이전트가 귀하를 대신하여 생성한 모든 자동 응답 콘텐츠("AI 출력")를 소유합니다. 당사는 귀하의 제품 가격, FAQ 또는 고객 대화 내역에 대해 소유권을 주장하지 않습니다.'
      },
      {
        heading: '4. Human-in-the-Loop 감독 책임',
        p: 'Regalia AI 모델은 정확하고 유용하며 정중한 지원을 제공하도록 정밀하게 설계되었으나, 인공지능 시스템은 간혹 엣지 케이스나 환각 현상을 겪을 수 있습니다. 귀하는 다음 사항을 인정합니다:',
        list: [
          '귀하는 실시간 WebSocket 대시보드 알림예: 시스템 경고 또는 폴백 트리거을 모니터링할 책임이 있습니다.',
          '귀하는 문제가 AI 신뢰도 임계값을 초과할 때 인간 개입(Human Takeover) 메커니즘을 활용하는 데 동의합니다.',
          'Regalia AI는 가격, 재고 수준 또는 배송 약속에 관한 검증되지 않은 자동 발언으로 인한 상업적 손실에 대해 책임을 지지 않습니다.'
        ]
      },
      {
        heading: '5. 서비스 수준 계약(SLA) 및 가용성',
        p: '당사는 FastAPI 웹훅 처리 서버 및 실시간 대시보드 연결에 대해 99.9%의 가용성을 유지하기 위해 노력합니다. 그러나 플랫폼 성능은 Meta의 WhatsApp Graph API 엔드포인트 및 Google DeepMind의 Gemini 클라우드 인퍼런스 서버를 포함한 제3자 인프라의 지속적인 가용성에 따라 달라집니다. 제3자 업스트림 제공업체로 인한 일시적인 중단은 본 약관의 위반으로 간주되지 않습니다.'
      },
      {
        heading: '6. 책임의 한계 및 면책',
        p: '관련 법률이 허용하는 최대 범위 내에서 Regalia AI 및 그 계열사는 자율 WhatsApp 에이전트 사용으로 인해 발생하는 이익, 데이터 또는 비즈니스 영업권의 손실을 포함한 간접적, 부수적, 특별, 결과적 또는 징벌적 손해에 대해 책임을 지지 않습니다. 귀하는 귀하의 Meta WhatsApp Business 정책 또는 관련 개인정보 보호법 위반으로 인해 발생하는 모든 제3자 청구 또는 규제 벌금으로부터 Regalia AI를 방어하고 면책하며 해를 입히지 않을 것에 동의합니다.'
      },
      {
        heading: '7. 준거법 및 연락처',
        p: '본 고객 서비스 약관은 법률 충돌 원칙과 관계없이 관련 상법의 적용을 받습니다. 행정적 문의, 엔터프라이즈 SLA 맞춤 설정 또는 법적 고지는 당사 법무팀(legal@regalia.ai)으로 문의하시기 바랍니다.'
      }
    ]
  },
  hi: {
    title: 'ग्राहक सेवा की शर्तें',
    effective: 'प्रभावी तिथि: 16 जुलाई 2026 · Regalia AI WhatsApp एजेंट SaaS प्लेटफ़ॉर्म',
    previousVersion: 'पिछला संस्करण',
    intro: 'ये ग्राहक सेवा शर्तें ("शर्तें") Regalia AI स्वायत्त WhatsApp ग्राहक सेवा प्लेटफ़ॉर्म जिसमें एप्लिकेशन प्रोग्रामिंग इंटरफेस, यूजर इंटरफेस और राउटिंग एल्गोरिदम शामिल हैं तक आपकी पहुँच और व्यावसायिक उपयोग को नियंत्रित करती हैं। अपने WhatsApp Business फ़ोन नंबर ID को पंजीकृत या कनेक्ट करके, आप इन शर्तों से बाध्य होने के लिए सहमत होते हैं।',
    sections: [
      {
        heading: '1. प्लेटफ़ॉर्म दायरा और AI स्वायत्त प्रसंस्करण',
        p: 'Regalia AI एक सॉफ़्टवेयर-एज़-ए-सर्विस (SaaS) समाधान प्रदान करता है जिसे बड़े भाषा मॉडल का उपयोग करके WhatsApp पर ग्राहक सेवा पूछताछ को स्वचालित करने के लिए डिज़ाइन किया गया है। सक्रिय होने के बाद, हमारा बैकएंड स्वचालित रूप से Meta से वेबहुक पेलोड प्राप्त करता है और आपके कॉन्फ़िगर किए गए नॉलेज बेस और बोली नियमों के आधार पर प्रासंगिक उत्तर उत्पन्न करता है।'
      },
      {
        heading: '2. Meta WhatsApp Business API अनुपालन और एंटी-स्पैम दायित्व',
        p: 'आप स्पष्ट रूप से गारंटी देते हैं और सहमत होते हैं कि Regalia SaaS प्लेटफ़ॉर्म का आपका उपयोग Meta WhatsApp Business सेवा शर्तों और Meta एंटी-स्पैम दिशानिर्देशों का सख्ती से पालन करेगा:',
        list: [
          'आप अवांछित थोक ब्रॉडकास्ट, अनधिकृत प्रचार संदेश या धोखाधड़ी वाले संचार भेजने के लिए Regalia AI का उपयोग नहीं करेंगे।',
          'आउटबाउंड स्वचालित WhatsApp वार्तालाप शुरू करने से पहले आपको अंतिम ग्राहकों से सत्यापन योग्य सहमति (ऑप्ट-इन) प्राप्त करनी होगी।',
          'अनुचित संदेश मात्रा या नीति उल्लंघन के परिणामस्वरूप Meta द्वारा लगाए गए किसी भी खाता प्रतिबंध, गुणवत्ता रेटिंग में गिरावट या प्रतिबंध के लिए आप पूरी तरह से उत्तरदायी बने रहेंगे।'
        ]
      },
      {
        heading: '3. इनपुट, नॉलेज बेस और AI आउटपुट का स्वामित्व',
        p: 'आपके और Regalia AI के बीच, आप अपने व्यावसायिक क्रेडेंशियल्स (, ), कस्टम नॉलेज बेस दस्तावेज़ों, और ग्राहक प्रॉम्प्ट इनपुट ("ग्राहक इनपुट") में सभी अधिकार, शीर्षक और बौद्धिक संपदा हित बनाए रखते हैं। इसी प्रकार, आप अपनी ओर से हमारे AI एजेंट द्वारा उत्पन्न सभी स्वचालित उत्तर सामग्री ("AI आउटपुट") के स्वामी हैं। हम आपके कस्टम उत्पाद मूल्य निर्धारण, अक्सर पूछे जाने वाले प्रश्नों या ग्राहक संचार इतिहास पर कोई मालिकाना दावा नहीं करते हैं।'
      },
      {
        heading: '4. Human-in-the-Loop पर्यवेक्षी जिम्मेदारी',
        p: 'हालांकि Regalia AI मॉडल को सटीक, उपयोगी और विनम्र सहायता प्रदान करने के लिए सख्ती से डिज़ाइन किया गया है, फिर भी कृत्रिम बुद्धिमत्ता प्रणालियों को कभी-कभी किनारे के मामलों (edge cases) या मतिभ्रम (hallucinations) का सामना करना पड़ सकता है। आप स्वीकार करते हैं कि:',
        list: [
          'आप वास्तविक समय के WebSocket डैशबोर्ड अलर्ट (जैसे, `anger_detected` या फ़ॉलबैक ट्रिगर) की निगरानी के लिए जिम्मेदार हैं।',
          'जब कोई समस्या AI विश्वास सीमा को पार कर जाती है, तो आप मानव अधिग्रहण (Human Takeover) तंत्र का उपयोग करने के लिए सहमत होते हैं।',
          'Regalia AI को मूल्य निर्धारण, स्टॉक स्तर या वितरण वादों के संबंध में असत्यापित स्वचालित बयानों के परिणामस्वरूप होने वाले व्यावसायिक नुकसान के लिए उत्तरदायी नहीं ठहराया जाएगा।'
        ]
      },
      {
        heading: '5. सेवा स्तर समझौता (SLA) और उपलब्धता',
        p: 'हम अपने FastAPI वेबहुक प्रसंस्करण सर्वर और वास्तविक समय डैशबोर्ड कनेक्शन के लिए 99.9% उपलब्धता बनाए रखने का प्रयास करते हैं। हालाँकि, प्लेटफ़ॉर्म का प्रदर्शन Meta के WhatsApp Graph API एंडपॉइंट्स और Google DeepMind के Gemini क्लाउड इन्फ़रेंस सर्वर सहित तीसरे पक्ष के बुनियादी ढांचे की निरंतर उपलब्धता पर निर्भर करता है। तीसरे पक्ष के अपस्ट्रीम प्रदाताओं के कारण होने वाले अस्थायी व्यवधान इन शर्तों का उल्लंघन नहीं मानते हैं।'
      },
      {
        heading: '6. दायित्व की सीमा और क्षतिपूर्ति',
        p: 'लागू कानून द्वारा अनुमत अधिकतम सीमा तक, न तो Regalia AI और न ही इसके सहयोगी स्वायत्त WhatsApp एजेंट के आपके उपयोग से उत्पन्न होने वाले किसी भी अप्रत्यक्ष, आकस्मिक, विशेष, परिणामी, या दंडात्मक नुकसान, जिसमें लाभ, डेटा या व्यावसायिक सद्भावना का नुकसान शामिल है, के लिए उत्तरदायी होंगे। आप Meta WhatsApp Business नीतियों या लागू गोपनीयता कानूनों के आपके उल्लंघन से उत्पन्न होने वाले किसी भी तीसरे पक्ष के दावों या नियामक जुर्माने के खिलाफ Regalia AI की रक्षा करने, क्षतिपूर्ति करने और उसे हानिरहित रखने के लिए सहमत होते हैं।'
      },
      {
        heading: '7. शासी कानून और संपर्क',
        p: 'ये ग्राहक सेवा शर्तें कानून के टकराव के सिद्धांतों के बिना लागू वाणिज्यिक कानूनों द्वारा शासित होती हैं। प्रशासनिक पूछताछ, एंटरप्राइज़ SLA अनुकूलन, या कानूनी नोटिस के लिए, कृपया हमारे कानूनी विभाग से legal@regalia.ai पर संपर्क करें।'
      }
    ]
  },
  ja: {
    title: '顧客利用規約',
    effective: '発効日: 2026年7月16日 · Regalia AI WhatsAppエージェントSaaSプラットフォーム',
    previousVersion: '以前のバージョン',
    intro: '本顧客利用規約（「本規約」）は、Regalia AI自律型WhatsAppカスタマーサービスプラットフォーム（`port 8000` エンドポイント、ダッシュボードUI、およびGemini AIエージェントルーティング）へのアクセスおよび商用利用を規定します。WhatsApp Business電話番号IDを登録または接続することにより、お客様は本規約に拘束されることに同意するものとします。',
    sections: [
      {
        heading: '1. プラットフォームの範囲およびAI自律処理',
        p: 'Regalia AIは、大規模言語モデル（`gemini-2.5-flash` / `gemini-3.1-pro`）を利用してWhatsApp上でのカスタマーサービス問い合わせを自動化するために設計されたサービスとしてのソフトウェア（SaaS）ソリューションを提供します。有効化（`is_active = 1`）されると、当社のバックエンドはMetaからWebhookペイロードを自動的に取り込み、設定されたナレッジベース（`knowledge_base`）および方言ルール（`toggle_slang`、`toggle_java`、`toggle_ongkir`、`toggle_anger`、および `toggle_fallback`）に基づき、文脈に応じた返信を生成します。'
      },
      {
        heading: '2. Meta WhatsApp Business APIの遵守およびスパム防止義務',
        p: 'お客様は、Regalia SaaSプラットフォームの利用がMeta WhatsApp Business利用規約およびMetaスパム防止ガイドラインを厳格に遵守することを明示的に保証し、同意します：',
        list: [
          'お客様は、Regalia AIを未承諾の大量配信、不正なプロモーションの一斉送信、または詐欺的な通信の送信に使用してはなりません。',
          'お客様は、発信型の自動WhatsApp対話を開始する前に、最終顧客から検証可能な事前承諾（オプトイン）を取得する必要があります。',
          '不適切なメッセージ量やポリシー違反に起因してMetaが課すアカウント制限、品質評価の低下、または利用停止については、お客様が単独で責任を負います。'
        ]
      },
      {
        heading: '3. 入力データ、ナレッジベース、およびAI出力の所有権',
        p: 'お客様とRegalia AIの間において、お客様のビジネス認証情報（、）、独自のナレッジベース文書、および顧客プロンプト入力（「顧客入力」）に対するすべての権利、権原、および知的財産権は、お客様に留保されます。同様に、当社のAIエージェントがお客様に代わって生成したすべての自動返信コンテンツ（「AI出力」）もお客様に帰属します。当社は、お客様の製品価格、FAQ、または顧客とのコミュニケーション履歴に対して所有権を主張しません。'
      },
      {
        heading: '4. Human-in-the-Loop 監督責任',
        p: 'Regalia AIのモデルは、正確で役立ち、丁寧なサポートを提供するように厳密に設計されていますが、人工知能システムはまれにエッジケースやハルシネーション（誤情報生成）に直面する場合があります。お客様は以下を承諾するものとします：',
        list: [
          'お客様は、リアルタイムのWebSocketダッシュボードアラート（例：`anger_detected` やフォールバックトリガー）を監視する責任があります。',
          '問題がAIの信頼度しきい値を超えた場合、お客様は人間による引き継ぎ（Human Takeover）メカニズムを活用することに同意します。',
          'Regalia AIは、価格、在庫水準、または配送約束に関する未検証の自動発言起因する商業的損失に対して法的責任を負わないものとします。'
        ]
      },
      {
        heading: '5. サービスレベルアグリーメント（SLA）および可用性',
        p: '当社は、FastAPI Webhook処理サーバーおよびリアルタイムダッシュボード接続（`/ws`）において99.9%の可用性を維持するよう努めます。ただし、プラットフォームのパフォーマンスは、MetaのWhatsApp Graph APIエンドポイントやGoogle DeepMindのGeminiクラウド推論サーバーを含むサードパーティインフラストラクチャの継続的な可用性に依存します。サードパーティの上流プロバイダーによる一時的な中断は、本規約の違反を構成しないものとします。'
      },
      {
        heading: '6. 責任の制限および補償',
        p: '適用法で認められる最大限の範囲において、Regalia AIおよびその関連会社は、自律型WhatsAppエージェントの使用から生じる利益、データ、または営業権の損失を含む、間接的、偶発적、特別、結果的、または懲罰的な損害について一切の責任を負いません。お客様は、Meta WhatsApp Businessのポリシーまたは適用されるプライバシー法規の違反に起因する第三者からの請求または規制上の罰金に対して、Regalia AIを防御、補償し、免責することに同意します。'
      },
      {
        heading: '7. 準拠法および連絡先',
        p: '本顧客利用規約は、法の抵触に関する原則に関わらず、適用される商法に準拠します。管理上の問い合わせ、エンタープライ즈SLAのカスタマイズ、または法的事項通知については、当社の法務担当（legal@regalia.ai）までご連絡ください。'
      }
    ]
  }
};
